sociably/config/routes.rb
Socially::Application.routes.draw do

	scope 'api' do
		scope 'v1' do
			use_doorkeeper
		end
	end

	namespace :api, defaults: { format: 'json' } do
		#/api/... Api::
		namespace :v1 do

			#use_doorkeeper

		  resources :topics

		  resources :tags

		  resources :subscriptions

		  resources :users

		  resources :tasks

		  root 'subscriptions#index'

		end
	end

  resources :books do
    resources :chapters
    resources :contributions
  end

  resources :people do
    resources :contributions
  end
  
  resources :publishers
  resources :roles
  resources :tags
  resources :tasks
  resources :topics

  devise_for :users, controllers: {confirmations: "confirmations", passwords: "passwords", registrations: "registrations", sessions: "sessions"}

  resources :users do
    resources :subscriptions, except: [:new, :edit], shallow: true
  end

  devise_scope :user do
  	root 'sessions#new'
  end
end

sociably/app/models/person.rb
class Person < ActiveRecord::Base
	has_many :contributions
	has_many :roles, through: :contributions

  def full_name
    first_name + " " + middle_name + " " + last_name
  end
end

sociably/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :middle_name, :last_name)
    end
end

sociably/app/helpers/people_helper.rb
module PeopleHelper
end

sociably/app/views/people/_form.html.haml
= form_for @person do |f|
  - if @person.errors.any?
    #error_explanation
      %h2= "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      %ul
        - @person.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label(:first_name)
    = f.text_field(:first_name)

  .field
    = f.label(:middle_name)
    = f.text_field(:middle_name)

  .field
    = f.label(:last_name)
    = f.text_field(:last_name)

  .actions
    = f.submit 'Save'

sociably/app/views/people/edit.html.haml
%h1 Editing person

= render 'form'

= link_to 'Show', @person
\|
= link_to 'Back', people_path

sociably/app/views/people/index.html.haml
%h1 Listing people

%table
  %tr
    %th
    %th
    %th

  - @people.each do |person|
    %tr
      %td
        = person.first_name
        = person.middle_name
        = person.last_name
      %td= link_to 'Show', person
      %td= link_to 'Edit', edit_person_path(person)
      %td= link_to 'Destroy', person, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Person', new_person_path

sociably/app/views/people/new.html.haml
%h1 New person

= render 'form'

= link_to 'Back', people_path

sociably/app/views/people/show.html.haml
%p#notice= notice

%p
	= @person.first_name
	= @person.middle_name
	= @person.last_name

= link_to 'Edit', edit_person_path(@person)
\|
= link_to 'Back', people_path
\|
= link_to 'Contributions', person_contributions_path(@person)