sociably/config/routes.rb
Socially::Application.routes.draw do

	scope 'api' do
		scope 'v1' do
			use_doorkeeper
		end
	end

	namespace :api, defaults: { format: 'json' } do
		#/api/... Api::
		namespace :v1 do

			#use_doorkeeper

		  resources :topics

		  resources :tags

		  resources :subscriptions

		  resources :users

		  resources :tasks

		  root 'subscriptions#index'

		end
	end

  resources :books do
    resources :chapters
    resources :contributions
  end

  resources :people do
    resources :contributions
  end
  
  resources :publishers
  resources :roles
  resources :tags
  resources :tasks
  resources :topics

  devise_for :users, controllers: {confirmations: "confirmations", passwords: "passwords", registrations: "registrations", sessions: "sessions"}

  resources :users do
    resources :subscriptions, except: [:new, :edit], shallow: true
  end

  devise_scope :user do
  	root 'sessions#new'
  end
end

sociably/app/models/role.rb
class Role < ActiveRecord::Base
	has_many :contributions
end

sociably/app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render action: 'show', status: :created, location: @role }
      else
        format.html { render action: 'new' }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:description, :id)
    end
end

sociably/app/helpers/roles_helper.rb
module RolesHelper
end

sociably/app/views/roles/_form.html.haml
= form_for @role do |f|
  - if @role.errors.any?
    #error_explanation
      %h2= "#{pluralize(@role.errors.count, "error")} prohibited this role from being saved:"
      %ul
        - @role.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label(:description)
    = f.text_field(:description)

  .actions
    = f.submit 'Save'

sociably/app/views/roles/edit.html.haml
%h1 Editing role

= render 'form'

= link_to 'Show', @role
\|
= link_to 'Back', roles_path

sociably/app/views/roles/index.html.haml
%h1 Listing roles

%table
  %tr
    %th
    %th
    %th

  - @roles.each do |role|
    %tr
      %td= role.description
      %td= link_to 'Show', role
      %td= link_to 'Edit', edit_role_path(role)
      %td= link_to 'Destroy', role, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Role', new_role_path

sociably/app/views/roles/new.html.haml
%h1 New role

= render 'form'

= link_to 'Back', roles_path

sociably/app/views/roles/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_role_path(@role)
\|
= link_to 'Back', roles_path