sociably/config/routes.rb
Socially::Application.routes.draw do

	scope 'api' do
		scope 'v1' do
			use_doorkeeper
		end
	end

	namespace :api, defaults: { format: 'json' } do
		#/api/... Api::
		namespace :v1 do

			#use_doorkeeper

		  resources :topics

		  resources :tags

		  resources :subscriptions

		  resources :users

		  resources :tasks

		  root 'subscriptions#index'

		end
	end

  resources :books do
    resources :chapters
    resources :contributions
  end

  resources :people do
    resources :contributions
  end
  
  resources :publishers
  resources :roles
  resources :tags
  resources :tasks
  resources :topics

  devise_for :users, controllers: {confirmations: "confirmations", passwords: "passwords", registrations: "registrations", sessions: "sessions"}

  resources :users do
    resources :subscriptions, except: [:new, :edit], shallow: true
  end

  devise_scope :user do
  	root 'sessions#new'
  end
end

sociably/app/models/publisher.rb
class Publisher < ActiveRecord::Base
	has_many :books
end

sociably/app/controllers/publishers_controller.rb
class PublishersController < ApplicationController

  before_action :set_publisher, only: [:show, :edit, :update, :destroy]

  # GET /pubishers
  # GET /publishers.json
  def index
    @publishers = Publisher.all
  end

  # GET /publishers/1
  # GET /publishers/1.json
  def show
  end

  # GET /publishers/new
  # GET /publishers/new.json
  def new
    @publisher = Publisher.new
  end

  # GET /publishers/1/edit
  def edit
  end

  # POST /publishers
  # POST /publishers.json
  def create
    @publisher = Publisher.new(publisher_params)

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to @publisher, notice: 'Publisher was successfully created.' }
        format.json { render action: 'show', status: :created, location: @publisher }
      else
        format.html { render action: 'new' }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publishers/1
  # PATCH/PUT /publishers/1.json
  def update
    respond_to do |format|
      if @publisher.update(publisher_params)
        format.html { redirect_to @publisher, notice: 'Publisher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pubisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishers/1
  # DELETE /publishers/1.json
  def destroy
    @publisher.destroy
    respond_to do |format|
      format.html { redirect_to publishers_url }
      format.json { head :no_content }
    end
  end

  private

  def publisher_params
    params.require(:publisher).permit(:name)
  end

  def set_publisher
    @publisher = Publisher.find(params[:id])
  end

end

sociably/app/views/publishers/_form.html.haml
= form_for @publisher do |f|
  - if @publisher.errors.any?
    #error_explanation
      %h2= "#{pluralize(@publisher.errors.count, "error")} prohibited this publisher from being saved:"
      %ul
        - @publisher.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label(:name)
    = f.text_field(:name)

  .actions
    = f.submit 'Save'

sociably/app/views/publishers/edit.html.haml
%h1 Editing tag

= render 'form'

= link_to 'Show', @tag
|
= link_to 'Back', tags_path

sociably/app/views/publishers/index.html.haml
%h1 Listing publishers

%table
  %tr
    %th
    %th
    %th
    %th

  - @publishers.each do |publisher|
    %tr
      %td
        = publisher.name
      %td= link_to 'Show', publisher
      %td= link_to 'Edit', edit_publisher_path(publisher)
      %td= link_to 'Destroy', publisher, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Publisher', new_publisher_path

sociably/app/views/publishers/new.html.haml
%h1 New publisher

= render 'form'

= link_to 'Back', publishers_path

sociably/app/views/publishers/show.html.haml
%p#notice

%p
  %strong Publisher name:
  = @publisher.name

= link_to 'Edit', edit_publisher_path(@publisher)
|
= link_to 'Back', publishers_path